# Generated by Django 5.1.5 on 2025-02-02 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, verbose_name='Gender')),
                ('airline', models.CharField(max_length=100, verbose_name='Airline')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='Flight Number')),
                ('departure', models.CharField(max_length=100, verbose_name='Departure City')),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to='flights.flight')),
            ],
        ),
    ]
