# Generated by Django 5.1.5 on 2025-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='class_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Class'),
        ),
    ]
